### ISSUE TITLE
基本編輯器試做

### ISSUE THREAD

**Issue by dopamine908** [dopamine908/math-sharing-frontend#1]
- [x] 打字區打字，顯示區即時渲染
- [x] 將原始資料帶入打字區，成功渲染（原始資料可能有跳脫字元，如果原始資料跳脫字元會影響的話，可能要找出替代格式，離如 \ -> \\）
- [x] 打字區域裡面可能會是題目描述＋數學區塊，所以可能需要用到 ng-katex 的 paragraph 來做
- [x] #2

[ng-katex demo page](https://garciparedes.me/ng-katex/)
[ng-katex github](https://github.com/garciparedes/ng-katex)
[katex org](https://katex.org/)

**Comment by SamJheng** [comment]
- [x]  i18n module add to project
- [x]  include tailwind css to project
- [x] git push commit 規範

**Comment by SamJheng** [comment]
- [ ] 左邊編輯器右邊顯示數學函示
- [ ] 數學函示的按鈕
- [x] 數學函示可以插入編輯器任意地點
